config/routes.rb
Cards::Application.routes.draw do
  # Admin routes ------------------------------------------------------
  namespace :admin do
    controller :user_sessions do
      get  '/sign_in'  => :new,     :as => 'new_user_session'
      post '/sign_in'  => :create,  :as => 'user_sessions'
      get  '/sign_out' => :destroy, :as => 'destroy_user_session'
    end

    resources :accounts,
      :only => %w(index)
    resources :paypal_accounts,
      :only => %w(new create)
    resources :justgiving_accounts,
      :only => %w(new create)

    resources :users,
      :only => %w(index new create)

    resources :stores,
      :only => %w(index new create show edit update) do
      resources :products,
        :only => %w(new create show edit update),
        :shallow => true do
        resources :packagings,
          :only => %w(new create),
          :shallow => true
        resources :transfers,
          :only => %w(new create),
          :shallow => true
      end
    end

    root :to => redirect('/admin/stores', :status => 302)
  end

  # Distributor routes ------------------------------------------------
  namespace :distributor do
    controller :user_sessions do
      get  '/sign_in'  => :new,     :as => 'new_user_session'
      post '/sign_in'  => :create,  :as => 'user_sessions'
      get  '/sign_out' => :destroy, :as => 'destroy_user_session'
    end

    resources :stores, :only => [:index, :show] do
      member do
        get :shipped
      end

      resources :orders, :only => [:update]
    end

    root :to => redirect('/distributor/stores', :status => 302)
  end

  # Donor routes ------------------------------------------------------
  scope '/:store_id', :as => 'store', :constraints => { :store_id => /[a-z][a-z]/ } do
    resources :items,
      :only => [:create, :destroy]

    namespace :checkout do
      controller :justgiving do
        post '/justgiving'         => :create, :as => 'justgiving'
        get  '/justgiving/address' => :address, :as => 'justgiving_address'
        put  '/justgiving/address' => :update_address
        get  '/justgiving/review'  => :review, :as => 'justgiving_review'
        put  '/justgiving'         => :donate
        get  '/justgiving'         => :complete
      end

      controller :paypal do
        post '/paypal'        => :create, :as => 'paypal'
        get  '/paypal/cancel' => :cancel
        get  '/paypal'        => :review
        put  '/paypal'        => :confirm
      end
    end

    resources :orders,
      :only => :show

    root :to => 'stores#show'
  end

  root :to => 'stores#index'
end

app/models/store.rb
class Store < ActiveRecord::Base
  scope :active, where(:active => true)

  belongs_to :account,
    :inverse_of => :store,
    :polymorphic => true

  has_many :carts,
    :inverse_of => :store

  has_many :distributors,
    :inverse_of => :stores,
    :source => :user,
    :through => :distributorships

  has_many :distributorships,
    :inverse_of => :store

  has_many :orders,
    :through => :carts

  has_many :products,
    :inverse_of => :store,
    :order => :created_at

  attr_accessible :account_type_slash_id
  attr_accessible :active
  attr_accessible :currency
  attr_accessible :description
  attr_accessible :distributor_ids
  attr_accessible :name
  attr_accessible :slug

  validates :currency,
    :presence => true
  validates :description,
    :presence => true
  validates :name,
    :presence => true
  validates :slug,
    :format => {
      :allow_blank => true,
      :with        => /\A[a-z][a-z]\z/ },
    :presence => true,
    :uniqueness => true

  delegate :type_slash_id,
    :allow_nil => true,
    :prefix => true,
    :to => :account

  def account_type_slash_id=(account_type_slash_id)
    self.account = Account.find(account_type_slash_id)
  end

  def to_param
    slug
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::ApplicationController
  def index
    @stores = Store.order(:name)
  end

  def new
    @store = Store.new(params[:store])
  end

  def create
    @store = Store.new(params[:store])
    if @store.save
      redirect_to admin_stores_path, :notice => t('.create.success')
    else
      render 'new'
    end
  end

  def show
    @store = Store.find_by_slug!(params[:id])
  end

  def edit
    @store = Store.find_by_slug!(params[:id])
  end

  def update
    @store = Store.find_by_slug!(params[:id])
    if @store.update_attributes(params[:store])
      redirect_to admin_store_path(@store), :notice => t('.update.success')
    else
      render 'edit'
    end
  end
end

app/controllers/distributor/stores_controller.rb
class Distributor::StoresController < Distributor::ApplicationController
  def index
    @stores = current_user.stores.all
  end

  def show
    @store = current_user.stores.find_by_slug!(params[:id])
  end

  def shipped
    @store = current_user.stores.find_by_slug!(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :load_store, :only => :show

  def index
    @stores = Store.active.order(:name)
  end

  def show
    # work done in before_filters; need this method for it to work?!
  end
end

app/views/admin/stores/_form.html.haml
= form_for [:admin, @store] do |form|
  - if @store.errors.present?
    .errors
      = @store.errors.full_messages.to_sentence.concat('.')
  .fields
    .field
      = form.label :name
      = form.text_field :name
    .field
      = form.label :slug
      = form.text_field :slug
    .field
      = form.label :currency
      = form.text_field :currency
    .field
      = form.label :description
      = form.text_area :description
    .field
      = form.label :account_type_slash_id
      = form.collection_select :account_type_slash_id, Account.all, :type_slash_id, :display_name
    .field
      = form.label :distributor_ids
      = form.collection_select :distributor_ids, User.all, :id, :email, {}, :multiple => true
    .field
      = form.label :active
      = form.check_box :active
  .buttons
    = form.submit

app/views/admin/stores/edit.html.haml
%h1
  = link_to @store.name, [:admin, @store]
  = ':'
  = t('.title')

= render 'form'

app/views/admin/stores/index.html.haml
%h1= t('.title')

%ul
  - @stores.each do |store|
    %li[store]= link_to store.name, [:admin, store]
  %li= link_to t('.new'), new_admin_store_path

app/views/admin/stores/new.html.haml
%h1= t('.title')

= form_for [:admin, @store] do |form|
  - if @store.errors.present?
    .errors
      = @store.errors.full_messages.to_sentence.concat('.')
  .fields
    .field
      = form.label :name
      = form.text_field :name
    .field
      = form.label :slug
      = form.text_field :slug
    .field
      = form.label :currency
      = form.text_field :currency
    .field
      = form.label :description
      = form.text_area :description
    .field
      = form.label :account_id
      = form.collection_select :account_id, Account.all, :type_slash_id, :display_name
    .field
      = form.label :distributor_id
      = form.collection_select :distributor_id, User.all, :id, :email
  .buttons
    = form.submit

app/views/admin/stores/show.html.haml
%h1= @store.name

%section
  %h2= t('.products')

  %table#products
    %tbody
      - @store.products.each do |product|
        %tr[product]
          %td= link_to(product.name, admin_product_path(product))
          %td= product.quantity

  %p= link_to t('.new.product'), new_admin_store_product_path(@store)

%section
  %h2= t('.distributors')
  %ul
    - @store.distributors.each do |user|
      %li[user]= user.email
    %li= link_to t('.edit'), edit_admin_store_path(@store)