config/routes.rb
Cards::Application.routes.draw do
  # Admin routes ------------------------------------------------------
  namespace :admin do
    controller :user_sessions do
      get  '/sign_in'  => :new,     :as => 'new_user_session'
      post '/sign_in'  => :create,  :as => 'user_sessions'
      get  '/sign_out' => :destroy, :as => 'destroy_user_session'
    end

    resources :accounts,
      :only => %w(index)
    resources :paypal_accounts,
      :only => %w(new create)
    resources :justgiving_accounts,
      :only => %w(new create)

    resources :users,
      :only => %w(index new create)

    resources :stores,
      :only => %w(index new create show edit update) do
      resources :products,
        :only => %w(new create show edit update),
        :shallow => true do
        resources :packagings,
          :only => %w(new create),
          :shallow => true
        resources :transfers,
          :only => %w(new create),
          :shallow => true
      end
    end

    root :to => redirect('/admin/stores', :status => 302)
  end

  # Distributor routes ------------------------------------------------
  namespace :distributor do
    controller :user_sessions do
      get  '/sign_in'  => :new,     :as => 'new_user_session'
      post '/sign_in'  => :create,  :as => 'user_sessions'
      get  '/sign_out' => :destroy, :as => 'destroy_user_session'
    end

    resources :stores, :only => [:index, :show] do
      member do
        get :shipped
      end

      resources :orders, :only => [:update]
    end

    root :to => redirect('/distributor/stores', :status => 302)
  end

  # Donor routes ------------------------------------------------------
  scope '/:store_id', :as => 'store', :constraints => { :store_id => /[a-z][a-z]/ } do
    resources :items,
      :only => [:create, :destroy]

    namespace :checkout do
      controller :justgiving do
        post '/justgiving'         => :create, :as => 'justgiving'
        get  '/justgiving/address' => :address, :as => 'justgiving_address'
        put  '/justgiving/address' => :update_address
        get  '/justgiving/review'  => :review, :as => 'justgiving_review'
        put  '/justgiving'         => :donate
        get  '/justgiving'         => :complete
      end

      controller :paypal do
        post '/paypal'        => :create, :as => 'paypal'
        get  '/paypal/cancel' => :cancel
        get  '/paypal'        => :review
        put  '/paypal'        => :confirm
      end
    end

    resources :orders,
      :only => :show

    root :to => 'stores#show'
  end

  root :to => 'stores#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :store,
    :inverse_of => :carts

  has_many :items,
    :inverse_of => :cart

  has_one :order,
    :inverse_of => :cart

  def compact!
    keep = {}

    items.each do |item|
      if kept = keep[item.packaging_id]
        kept.increment!(:quantity, item.quantity)
        item.destroy
      else
        keep[item.packaging_id] = item
      end
    end

    self
  end

  def empty?
    items.blank?
  end

  def mutable?
    order.blank?
  end

  def total
    items.inject(0) { |total, item| total += item.price }
  end
end

app/views/carts/_cart.html.haml
%table.cart
  %tbody
    - cart.items.order(:created_at).each do |item|
      %tr[item]
        %td= item.product_name
        %td= item.name
        %td= item.quantity
        %td.price= format_currency(item.price, cart.store.currency)
        - if cart.mutable?
          %td= button_to(t('.remove'), [@store, item], :method => :delete)
        - if current_user.try(:distributor?)
          %td
            - if item.shipped_at?
              %time{:datetime => item.shipped_at.to_s(:html5)}
                = t('.time', :time => time_ago_in_words(item.shipped_at))
            - elsif defined?(f) && f.try(:respond_to?, :fields_for)
              = f.fields_for(:items, item) do |fields|
                = fields.check_box :shipped_at, {}, Time.zone.now.to_s(:db)
            - else
              &nbsp;

  %tfoot
    %tr
      %td.total{:colspan => 3}= t('.total')
      %td.price= format_currency(cart.total, cart.store.currency)
      - if cart.mutable?
        %td &nbsp;
      - if current_user.try(:distributor?)
        %td &nbsp;

app/views/carts/_summary.html.haml
%p
  You have
  = pluralize current_cart.quantity, 'item'
  in your cart:
%ul
  - current_cart.items.each do |item|
    %li
      = item.quantity
      = item.product_name
      = item.variant.name
      = item.total.exchange_to(current_currency)
%p
  Cart total:
  = current_cart.total.exchange_to(current_currency)

%ul
  %li= link_to 'Update Quantities', edit_cart_path
  %li= link_to 'Proceed to Checkout', checkout_path

app/views/carts/edit.html.haml
- form_for @cart, :url => cart_path do |f|
  %table
    %thead
      %tr
        %th
        %th
        %th Unit
        %th Qty
        %th Total
        %th
    %tbody
      - @cart.items.each do |item|
        %tr
          - fields_for 'items[]', item do |fields|
            %td= item.product_name
            %td= item.variant_description
            %td= item.variant_price
            %td= fields.text_field :quantity
            %td= item.total
            %td= link_to 'Remove', item, :method => :delete
    %tfoot
      %tr
        %td
        %td
        %td
        %td
        %td= @cart.total

  = f.submit 'Update Quantities'